### ISSUE TITLE
Edge Rails + postgresql + ancestry 3.1.0: `subtree` and `subtree_ids` methods fail.

### ISSUE THREAD

**Issue by khustochka** [stefankroes/ancestry#503]
Hello,

I have an app on Edge Rails and using Postgres as DB.

Starting with ancestry v 3.1.0 calls to `subtree` and `subtree_ids` in my app started to fail with the following error:

````
NoMethodError: undefined method `new' for Arel::Nodes:Module
    ancestry (3.1.0) lib/ancestry/materialized_path.rb:81:in `ordered_by_ancestry'
    ancestry (3.1.0) lib/ancestry/instance_methods.rb:272:in `subtree'
    ancestry (3.1.0) lib/ancestry/instance_methods.rb:276:in `subtree_ids'
````

I have created an executable test case: https://gist.github.com/khustochka/591c0dee826a95a42dfbe0d0c136a1a2

Environment: 

Rails: edge (6.1.0.alpha)
DB adapter: Postgresql
Ancestry: 3.1.0

Please note, this is not reproduced if at least one of these conditions is not met, i.e. it works fine on Rails 6.0.x, or on ancestry 3.0.7, or with SQLite.

Thank you!

**Comment by kbrock** [comment]
thanks for the reproducer. made it very easy to fix
