### ISSUE TITLE
Getting error after update from 3.0.4 to 3.0.7

### ISSUE THREAD

**Issue by AllanKlaus** [stefankroes/ancestry#446]
I was updating my app and started to get error when update from 3.0.4 to  3.0.7.

My problem is because i'm working with a legacy database and the ancestry was created as a integer. I can't  update the database because other application use it.

the error is

```
NoMethodError:
        undefined method `split' for 13654:Fixnum
      # /home/klaus/.rvm/gems/ruby-2.3.1/gems/ancestry-3.0.7/lib/ancestry/instance_methods.rb:381:in `parse_ancestry_column'
      # /home/klaus/.rvm/gems/ruby-2.3.1/gems/ancestry-3.0.7/lib/ancestry/instance_methods.rb:153:in `ancestor_ids'
```

I saw the in the version `v3.0.5` was changed the method `parse_ancestry_column` and removed the `to_s` on obj. I think it's a breaking change, and cant be done in a patch update. 

I created a pull request to return the `to_s` and avoid this breaking change.

**Comment by kbrock** [comment]
merged
